name: Build Apps

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build Vite app
      run: npm run build
      
    - name: Build Mac app
      run: npm run dist:mac
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEBUG: electron-builder
    
    - name: List release contents
      if: always()
      run: |
        echo "=== Release directory ==="
        ls -la release/ || echo "No release folder"
        echo "=== All DMG files ==="
        find . -name "*.dmg"
      
    - name: Upload Mac app
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: mac-app
        path: release/*.dmg

  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build Vite app
      run: npm run build
      
    - name: Build Windows app
      run: npm run dist:win
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEBUG: electron-builder
    
    - name: List release contents
      if: always()
      shell: bash
      run: |
        echo "=== Release directory ==="
        ls -la release/ || echo "No release folder"
        echo "=== All EXE files ==="
        find . -name "*.exe"
      
    - name: Upload Windows app
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: windows-app
        path: release/*.exe